package com.integreight.onesheeld.sdk;

public enum OneSheeldError {
    BLUETOOTH_NOT_ENABLED,
    BLUETOOTH_NOT_SUPPORTED,
    DEVICE_NOT_CONNECTED,
    SCANNING_IN_PROGRESS,
    PENDING_CONNECTION_IN_PROGRESS,
    NON_COMPATIBLE_FIRMWARE_VERSION,
    NEW_FIRMWARE_IS_AVAILABLE,
    MAXIMUM_BLUETOOTH_CONNECTIONS_REACHED,
    ALREADY_CONNECTED_TO_THAT_DEVICE,
    BLUETOOTH_CONNECTION_FAILED
}
