language: android

android:
  components:
    - tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra
    - platform-tools
    - tools
    - extra-android-support
    - extra-google-google_play_services

jdk:
    - oraclejdk8

before_script:
  - chmod +x gradlew
  - touch local.properties

script: ./gradlew assemble

notifications:
  email:
    on_success: change
    on_failure: change